# Appendix 3: Python Libraries Crash Course

## Part 2: Multi-Dimensional Numpy Arrays

### Nested Lists

In [1]:
project_1 = [-200, 20, 50, 70, 100, 50]
project_2 = [-50, 10, 25, 25, 50]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [2]:
all_proj = [project_1, project_2, project_3]

In [3]:
all_proj

[[-200, 20, 50, 70, 100, 50],
 [-50, 10, 25, 25, 50],
 [-1000, 200, 200, 300, 500, 500, 750, 250]]

In [4]:
type(all_proj)

list

In [5]:
len(all_proj)

3

In [6]:
all_proj[0]

[-200, 20, 50, 70, 100, 50]

In [7]:
all_proj[2]

[-1000, 200, 200, 300, 500, 500, 750, 250]

In [8]:
all_proj[-1]

[-1000, 200, 200, 300, 500, 500, 750, 250]

In [9]:
all_proj[:2]

[[-200, 20, 50, 70, 100, 50], [-50, 10, 25, 25, 50]]

In [10]:
all_proj[-2:]

[[-50, 10, 25, 25, 50], [-1000, 200, 200, 300, 500, 500, 750, 250]]

In [11]:
all_proj[0][0]

-200

In [22]:
all_proj[3][3]

IndexError: list index out of range

In [14]:
I0 = []
for proj in all_proj:
    I0.append(proj[0])

In [ ]:
I0

### 2-dim Numpy Arrays

In [23]:
import numpy as np

In [24]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]
nl = [cf1, cf2, cf3]

In [26]:
nl

[[-200, 20, 50, 70, 100, 50],
 [-150, 25, 60, 50, 50, 40],
 [-250, 10, 25, 50, 125, 200]]

In [27]:
np.array(nl)

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [28]:
cfs = np.array(nl)

In [29]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [30]:
type(cfs)

numpy.ndarray

In [31]:
cfs.shape

(3, 6)

In [32]:
cfs[0]

array([-200,   20,   50,   70,  100,   50])

In [33]:
cfs[-1]

array([-250,   10,   25,   50,  125,  200])

In [34]:
cfs[1:]

array([[-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [35]:
cfs[0][0]

-200

In [36]:
cfs[0, 0]

-200

### Slicing 2-dim Numpy Arrays (Part 1)

In [37]:
import numpy as np

In [38]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]

In [39]:
cfs = np.array([cf1, cf2, cf3])
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [63]:
cfs.shape

(3, 6)

In [64]:
cfs[:, 0]

array([-200, -150, -250])

In [65]:
cfs[:, -1]

array([ 50,  40, 200])

In [66]:
cfs[:, :2]

array([[-200,   20],
       [-150,   25],
       [-250,   10]])

In [67]:
cfs[2, 1:]

array([ 10,  25,  50, 125, 200])

In [68]:
cfs[-2:, :2]

array([[-150,   25],
       [-250,   10]])

In [50]:
project_1 = [-200, 20, 50, 70, 100, 50]
project_2 = [-50, 10, 25, 25, 50]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [51]:
array = np.array([project_1, project_2, project_3])

X:\Temp/ipykernel_19400/1645949024.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array = np.array([project_1, project_2, project_3])


In [53]:
array

array([list([-200, 20, 50, 70, 100, 50]), list([-50, 10, 25, 25, 50]),
       list([-1000, 200, 200, 300, 500, 500, 750, 250])], dtype=object)

In [54]:
array.shape

(3,)

In [ ]:
# array[:, 0]

In [55]:
project_1 = np.array([-200, 20, 50, 70, 100, 50, 0, 0])
project_2 = np.array([-50, 10, 25, 25, 50, 0, 0, 0])
project_3 = np.array([-1000, 200, 200, 300, 500, 500, 750, 250])

In [56]:
projects = np.array([project_1, project_2, project_3])

In [57]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [58]:
projects.shape

(3, 8)

In [59]:
projects[:, 0]

array([ -200,   -50, -1000])

In [60]:
project_1 = np.array([-200, 20, 50, 70, 100, 50])

In [61]:
project_1.resize(8)

In [62]:
project_1

array([-200,   20,   50,   70,  100,   50,    0,    0])

### Slicing 2-dim Numpy Arrays (Part 2)

In [69]:
import numpy as np

In [70]:
cf1 = np.array([-200, 20, 50, 70, 100, 50])
cf2 = np.array([-150, 25, 60, 50, 50, 40])
cf3 = np.array([-250, 10, 25, 50, 125, 200])

In [71]:
cfs = np.array([cf1, cf2, cf3])
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [72]:
cf1[[0, 3, -1]]

array([-200,   70,   50])

In [73]:
cfs[[0,-1], 0]

array([-200, -250])

In [74]:
cfs[0, [0, 2, -1]]

array([-200,   50,   50])

### Recap: Changing Elements in a Numpy Array / slice

In [75]:
import numpy as np


In [76]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]

In [77]:
cfs = np.array([cf1, cf2, cf3])
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [78]:
cfs[:, 0] = -200

In [79]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-200,   25,   60,   50,   50,   40],
       [-200,   10,   25,   50,  125,  200]])

In [80]:
cfs[:, 0] = cfs[:, 0] - 10

In [81]:
cfs

array([[-210,   20,   50,   70,  100,   50],
       [-210,   25,   60,   50,   50,   40],
       [-210,   10,   25,   50,  125,  200]])

In [82]:
cfs[:, 0] = [-200, -150, -250]

In [83]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [84]:
I0s = cfs[:, 0]
I0s

array([-200, -150, -250])

In [85]:
I0s[0] = -180
I0s

array([-180, -150, -250])

In [86]:
cfs

array([[-180,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [87]:
cf5 = cfs[:, -1].copy()
cf5

array([ 50,  40, 200])

In [88]:
cf5[-1] = 150
cf5

array([ 50,  40, 150])

In [89]:
cfs

array([[-180,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

### Row- and Column wise operations

In [90]:
import numpy as np
np.set_printoptions(precision=2, suppress= True)

In [91]:
project_1 = [-200, 20, 50, 70, 100, 50, 0, 0]
project_2 = [-50, 10, 25, 25, 50, 0, 0, 0]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [92]:
projects = np.array([project_1, project_2, project_3])

In [93]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [94]:
np.sum(projects)

1850

In [95]:
np.sum(projects, axis = 0)

array([-1250,   230,   275,   395,   650,   550,   750,   250])

In [96]:
np.sum(projects, axis = 1)

array([  90,   60, 1700])

In [97]:
np.cumsum(projects, axis = 1)

array([[ -200,  -180,  -130,   -60,    40,    90,    90,    90],
       [  -50,   -40,   -15,    10,    60,    60,    60,    60],
       [-1000,  -800,  -600,  -300,   200,   700,  1450,  1700]],
      dtype=int32)

In [98]:
np.mean(projects, axis = 1)

array([ 11.25,   7.5 , 212.5 ])

In [99]:
np.mean(projects, axis = 0)

array([-416.67,   76.67,   91.67,  131.67,  216.67,  183.33,  250.  ,
         83.33])

In [100]:
np.mean(projects)

77.08333333333333